remote_theme: pages-themes/cayman@v0.2.0
title: Курс "Компьютерный Практикум на python"
description: Сайт разработал Угарин Никита Александрович
show_downloads: true
github:
  zip_url: https://mykaleidoscope.ru/x/uploads/posts/2022-10/1666328852_41-mykaleidoscope-ru-p-dovolnaya-morda-kota-krasivo-45.jpg
